version: "3.7"
services:
  app:
    build:
      context: .
      #dockerfile: Dockerfile.alpine
      #dockerfile: Dockerfile.slim
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL:        mysql2://root:mysql123@db:3306/kiribori_sample?encoding=utf8mb4&prepared_statements=true
      REDIS_URL:           redis://redis:6379/1
    tmpfs:
      - /var/rails/tmp

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: kiribori_sample

  redis:
    image: redis
    ports:
      - "6379:6379"
